services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - softeam-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "published-news-articles:16:1,live-ohlc-feed:16:1,suggested-trades:16:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka
    depends_on:
      - zookeeper
    networks:
      - softeam-network
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    container_name: redis-server
    networks:
      - softeam-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  rebrow:
    image: marian/rebrow
    container_name: rebrow
    ports:
      - "5001:5001"
    networks:
      - softeam-network
    depends_on:
      - redis

  mysql:
    image: mysql:latest
    container_name: softeam-sql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: softeam
      MYSQL_USER: ${MYSQL_USER}          
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  
      TZ: "Asia/Kolkata"
    command: --pid-file=/var/run/mysqld/mysqld.pid
    networks:
      - softeam-network       
    ports:
      - "3307:3306"                         
    volumes:
      - softeam_db_data:/var/lib/mysql
      - ./SQL-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./SQL-scripts/dump_to_csv.sh:/docker-entrypoint-initdb.d/dump_to_csv.sh  # Dump script
      # - ./csv_dumps:/var/lib/mysql-files        # Dump storage 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  mission-control:
    build:
      context: ./Mission-Control/
      args:
        WORKER_COUNT: ${WORKER_COUNT:-8}
    container_name: Mission-Control
    env_file: 
      - ./Mission-Control/.env
    networks:
      - softeam-network
    ports:
      - "8081:8081"
      - "5679:5679"
    environment:
      DEBUG_MODE: ${DEBUG_MODE:-false}
      UPSTOX_CLIENT_ID: ${UPSTOX_CLIENT_ID}
      UPSTOX_REDIRECT_URI: ${UPSTOX_REDIRECT_URI}
      UPSTOX_CLIENT_SECRET: ${UPSTOX_CLIENT_SECRET}
      KITE_PASSWORD: ${KITE_PASSWORD}
      KITE_USER_ID: ${KITE_USER_ID}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 15s
      timeout: 15s
      retries: 20

  market-gateway:
    build:
      context: ./Market-Gateway/
      args:
        WORKER_COUNT: ${WORKER_COUNT:-8}
    container_name: Market-Gateway
    stop_grace_period: 5s
    networks:
      - softeam-network
    ports:
      - "8085:8085"
      - "5683:5683"
    environment:
      DEBUG_MODE: ${DEBUG_MODE:-false}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: softeam
      MYSQL_USER: ${MYSQL_USER}          
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  
    volumes:
      - softeam_runtime_data:/app/data
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
      mission-control:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/health"]
      interval: 15s
      timeout: 15s
      retries: 20

  technisight:
    build:
      context: ./TechniSight/
      args:
        WORKER_COUNT: ${WORKER_COUNT:-8}
    container_name: TechniSight
    networks:
      - softeam-network
    ports:
      - "8082:8082"
      - "5680:5680"
    environment:
      DEBUG_MODE: ${DEBUG_MODE:-false}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: softeam
      MYSQL_USER: ${MYSQL_USER}          
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  
    volumes:
      - softeam_runtime_data:/app/data
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      mission-control:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]  # Adjust this to fit your container's health check logic
      interval: 15s
      timeout: 15s
      retries: 20

  trading-engine:
    build:
      context: ./Trading-Engine/
      args:
        WORKER_COUNT: ${WORKER_COUNT:-8}
    container_name: Trading-Engine
    networks:
      - softeam-network
    ports:
      - "8083:8083"
      - "5681:5681"
    environment:
      DEBUG_MODE: ${DEBUG_MODE:-false}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: softeam
      MYSQL_USER: ${MYSQL_USER}          
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      mission-control:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]  # Adjust this to fit your container's health check logic
      interval: 15s
      timeout: 15s
      retries: 20

  news-gateway:
    build:
      context: ./News-Gateway/
      args:
        WORKER_COUNT: ${WORKER_COUNT:-8}
    container_name: News-Gateway
    networks:
      - softeam-network
    ports:
      - "8084:8084"
      - "5682:5682"
    environment:
      DEBUG_MODE: ${DEBUG_MODE:-false}
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      mission-control:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/health"]  # Adjust this to fit your container's health check logic
      interval: 15s
      timeout: 15s
      retries: 20

networks:
  softeam-network:
    driver: bridge

volumes:
  softeam_db_data:
  softeam_runtime_data:
    driver: local